#
#   Copyright 2017-2019 University of Virginia
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

# 
# import and create a copy of the environment so we don't screw up anyone elses env.
#
Import('irdb_env')
myenv=irdb_env.Clone()


# 
# input fies and program name
#
files=Glob( Dir('.').srcnode().abspath+"/*.cpp")
pgm_name="libstack_stamp.so"


# 
# add extra libraries needed for stack stamping
#
myenv.Append(LIBS=Split(" irdb-cfg irdb-util "))

# 
# build, and install the program by default
#
pgm=myenv.SharedLibrary(pgm_name,  files)
install=myenv.Install("$INSTALL_PATH/", pgm)
Default(install)

# 
# and we're done
# 
Return('install')
